input_dir: "data/aclImdb/temp_train"
output_dir: "output/sequence_classification"
model_dir: "/media/disk2/public/bert-base-uncased"
logging_dir: "output/sequence_classification/log"
seed: 42
learning_rate: 2e-5
per_device_train_batch_size: 8
per_device_eval_batch_size: 16
num_train_epochs: 10
weight_decay: 0.01
fp16: true
max_seq_length: 512
evaluation_strategy: "steps"
save_strategy: "steps"
trainer_logging_steps: 10
trainer_save_steps: 10
trainer_eval_steps: 10
warmup_steps: 10
save_total_limit: 1
early_stopping_patience: 5
metric_for_best_model: "accuracy"
debug: false
